    ########################################################
# creates postgres sql database image and pgadmin4 image
# login db: postgres:postgres hostname: postgres
# login pgadmin: admin@developer-blog.net:admin port 5555
#
# Added by Filip Kovacevic:
# - environment variable configurations
# - build section
# - Dockerfile
########################################################
version: '3'
services:
  #create_db:
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile
    
  postgres:
    image: postgres:14.2
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: saiks
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: saiks2022
      POSTGRES_PASSWORD: saiks2022
      POSTGRES_DB: football
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  load_data:
    build: 
      context: scripts/
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    volumes:
      - ./Datasets:/home/saiks/Datasets
      - ./scripts/import_data.py:/home/saiks/scripts/import_data.py
    restart: on-failure
    entrypoint: ["python3", "/home/saiks/scripts/import_data.py"]

  #pgadmin:
  #  image: dpage/pgadmin4
  #  depends_on:
  #    - postgres
  #  ports:
  #    - 5555:80
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@developer-blog.net
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  restart: unless-stopped

volumes:
  postgres-data:
  Datasets:
